[theme]
primaryColor = "#0078d7"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
